### ISSUE TITLE
tensor board使用随机端口，在内网无法访问

### ISSUE THREAD

**Issue by sandflee** [Qihoo360/XLearning#19]
公司内网环境只有审批后才能访问对应host:port, tensor board使用随机端口导致无法访问

**Comment by sandflee** [comment]
第二种方式，用户还是需要一个export的端口才能查看tensorboard。在360内部是怎么解决这个问题的呢？  
通过AM proxy的方式可行不？

**Comment by liyuance** [comment]
@sandflee 第二种方法需要找一个能访问HDFS的机器，指定端口指定tensorboard进程就可以了，如果你们公司网络端口有限制的话，你可以用nginx之类做个代理。
