### ISSUE TITLE
自定义estimator，任务无法执行

### ISSUE THREAD

**Issue by rainbow2301** [Qihoo360/XLearning#38]
按照官网自定义estimator的方法写了model_fn，在xlearning上无法执行，有人试过自定义estimator成功执行的吗？

官网例子如下：
https://www.tensorflow.org/get_started/custom_estimators

**Comment by jiarunying** [comment]
本地可以成功执行吗？若本地能成功跑通，从日志分析失败的原因信息

**Comment by Lihengwannafly** [comment]
您好，我现在也自定义estimator，但是到了Client: container container_e09_1546412828500_0017_01_000005 status is RUNNING这一步就报错。不知道您是不是相同的问题呢？
