### ISSUE TITLE
自定义任务，在xl-submit中通过--files提交了多个脚本，但works里仍然提示找不到需要的的脚本

### ISSUE THREAD

**Issue by sekingme** [Qihoo360/XLearning#39]
如图，提交命令里已经包括conv3d_utils.py文件。
![image](https://user-images.githubusercontent.com/12440815/41601931-374e5b00-740c-11e8-92f1-f6695674ab3d.png)

但提交任务后失败，某个work的日志显示缺了conv3d_utils.py文件。
![image](https://user-images.githubusercontent.com/12440815/41601979-5bfe7af2-740c-11e8-8676-654f3f355c39.png)

可明明已经提交上去了啊，这是什么问题？

**Comment by jiarunying** [comment]
1）在所执行的机器节点的对应路径下，看该文件是否成功上传；
2）在python脚本中添加 sys.path.append(os.getcwd())
