### ISSUE TITLE
model_fn()  中 if mode == tf.estimator.ModeKeys.PREDICT:  不支持

### ISSUE THREAD

**Issue by lin65505578** [Qihoo360/XLearning#40]
model = tf.estimator.Estimator(...)
ps=model.predict(...)

xlearning好像直接跳过 ps=model.predict(...) 不执行，直接显示success

mode_fn()   中tf.estimator.ModeKeys.PREDICT 模块加print 函数，在日志中没有看到print 输出的内容
用 model.eval(...) ,在model_fn(） 中的 print内容能打印出来，
从这些现象看 model.predict(...) 确实被忽略了

**Comment by Olivia-github** [comment]
> 解决了问题

您好，我碰到了同样的问题，请问您是如何解决的呢？
