### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by gogasca** [Qihoo360/XLearning#68]
I see that Hadoop 3.1 is not supported or listed.
Has this been tested with Hadoop 3.1 or how can I run TF training jobs using GPU?

**Comment by jiarunying** [comment]
XLearning support the gpu scheduled based on the hadoop 3.1.0+. More details: [r1.3-gpu](https://github.com/Qihoo360/XLearning/tree/r1.3-gpu)

**Comment by gogasca** [comment]
@jiarunying thanks for responding.
